name: deploy cloudformation stack

on:
  push:
    branches: [ main ]
    paths:
      - "infra/**"
      - ".github/workflows/deploy-infra.yml"

  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types: [completed]
  
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::939503809934:role/GithubActionsCICDRole
          aws-region: ap-southeast-2

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Deploy CloudFormation Stack
        env:
          IMAGE_URI: 939503809934.dkr.ecr.ap-southeast-2.amazonaws.com/helloapp:latest
        run: |
          aws cloudformation deploy \
            --stack-name helloapp-stack \
            --template-file infra/infra.yml \
            --capabilities CAPABILITY_NAMED_IAM

          aws ecs update-service \
            --cluster helloapp-cluster \
            --service helloapp-service \
            --force-new-deployment